name: Welcome Workflow

on: [push]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Initialize Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.2
    - name: Apply Terraform
      run: terraform apply -auto-approve
    - name: Destroy Terraform
      run: terraform destroy -auto-approve
